name: Bloglist deployment pipeline

on:
    push:
        branches:
            - main
    pull_request:
        branches: [main]
        types: [opened, synchronize]

jobs:
    setup_and_test:
        runs-on: ubuntu-latest

        services:
            mongodb:
                image: mongo:8
                ports:
                - 27017:27017

        env:
            MONGODB_URI: mongodb://localhost:27017/blogapp-test
            TEST_MONGODB_URI: mongodb://localhost:27017/blogapp-test
            SECRET: ${{ secrets.SECRET }}
            PORT: 3001

        steps:
            - uses: actions/checkout@v6
            - uses: actions/setup-node@v6
              with:
                node-version: '24'

            - name: Install root dependencies
              run: npm install

            - name: Install server dependencies
              working-directory: ./server
              run: npm install  

            - name: Testing server
              working-directory: ./server
              run: npm run test:conc
              
            - name: Install frontend dependencies
              working-directory: ./client
              run: npm install

            - name: Frontend ESLint
              working-directory: ./client
              run: npm run lint

            - name: Testing client
              working-directory: ./client
              run: npm run test

            - name: Build
              working-directory: ./client
              run: npm run build

            - name: Install e2e dependencies
              working-directory: ./e2e
              run: npm install

            - name: Install Playwright Browsers
              working-directory: ./e2e
              run: npx playwright install --with-deps

            - name: Run Playwright tests
              working-directory: ./e2e
              run: npx playwright test

            - uses: actions/upload-artifact@v4
              if: ${{ !cancelled() }}
              with:
                name: playwright-report
                path: e2e/playwright-report/
                retention-days: 30
    
    deploy:
      needs: [setup_and_test]
      runs-on: ubuntu-latest
      steps:
        - name: Trigger deployment
          if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ','), '#skip') }}
          run: curl ${{secrets.RENDER_DEPLOY_HOOK}}

    notify_success:
      needs: [deploy]
      runs-on: ubuntu-latest
      if: ${{ github.event_name == 'push' && success() }}
      steps:
        - name: Success notification
          uses: sarisia/actions-status-discord@v1        
          with:
            webhook: ${{ secrets.WEBHOOK_URL }}
            status: ${{ job.status }}
            nodetail: true
            content: "✅Deployment successful!" 
            title: "deployment"
            description: |
              **Commit:** ${{ github.sha}}
              **Message:** ${{ github.event.head_commit.message }}
              **Author:** ${{ github.event.head_commit.author.name }}
    
    notify_failure:
      needs: [setup_and_test, deploy]
      runs-on: ubuntu-latest
      if: ${{ always() && failure() }}
      steps: 
        - name: Failure notification
          uses: sarisia/actions-status-discord@v1
          with:
            webhook: ${{ secrets.WEBHOOK_URL }}
            status: ${{ job.status }}
            nodetail: true
            content: "Build Failed!" 
            title: "Failure Details"
            description: |
              **Repo:** ${{ github.repository }}
              **Branch:** ${{ github.ref_name }}
              **Commit:** ${{ github.sha }}
              **Message:** ${{ github.event.head_commit.message }}
              **Author:** ${{ github.event.head_commit.author.name }}
              **Workflow:** ${{ github.workflow }}
              **Job:** ${{ github.job }}
              [View Commit](${{ github.event.head_commit.url }}) 
              [View Run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})

    tag_release:
      needs: [deploy]
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v6
        - name: Bump version and push tag
          uses: anothrNick/github-tag-action@4ed44965e0db8dab2b466a16da04aec3cc312fd8
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            DEFAULT_BUMP: patch